server:
  port: 8081

spring:
  application:
    name: patient-ms
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:patient-ms-db}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user123}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS

info:
  application:
    name: patient-ms
    version: '@project.version@'

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/logs.log